name: Weekly Stock Screening

on:
  schedule:
    # Run every Sunday at 2 AM UTC (7:30 AM IST)
    - cron: '0 2 * * 0'
  workflow_dispatch:  # Allow manual trigger

jobs:
  screen-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock screening
        run: |
          python scripts/automated_screening.py

      - name: Upload screening results
        uses: actions/upload-artifact@v3
        with:
          name: screening-results
          path: |
            screening_results.pkl
            screening_results_*.csv
          retention-days: 30

      - name: Commit results (if configured)
        if: github.event_name == 'schedule'  # Only for scheduled runs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name: "GitHub Action"
          git add screening_results_*.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto: Weekly screening results $(date +'%Y-%m-%d')"
          # Note: Push disabled by default for safety
          # git push
